title: Rohan Shah
url: "https://rohanshah8.github.io"
baseurl: ""
description: >-
  My personal blog where I share thoughts on technology, life, and building things.

remote_theme: daviddarnes/garth
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
